[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.1"
nalgebra = "0.31.4"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.3"
